workflows:
  android-app:
    name: Unsigned AAB Build
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.example.soa"
    scripts:
      - name: Build Unsigned AAB
        script: |
          ./gradlew clean
          ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/bundle/**/*.aab
