workflows:
  build-aab:
    name: Build AAB for Play Store
    max_build_duration: 30
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Make Gradle executable
        script: chmod +x gradlew

      - name: Build AAB
        script: |
          ./gradlew clean
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - mitba.prashant@gmail.com
