workflows:
  android-app:
    name: Build AAB with Gradle wrapper
    max_build_duration: 30
    scripts:
      - name: Make wrapper executable
        script: |
          chmod +r gradlew
      - name: Build AAB (wrapper)
        script: |
          ./gradlew clean
          ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/bundle/**/*.aab
