workflows:
  android-app:
    name: Signed AAB Build
    environment:
      vars:
        KEYSTORE_B64: $KEYSTORE_B64
        KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
        KEY_PASSWORD: $KEY_PASSWORD
      android_signing:
        - soa.b64 # or remove this if using base64 method
    scripts:
      - name: Decode Keystore
        script: |
          echo "$KEYSTORE_B64" | base64 -d > keystore.jks
      - name: Build AAB
        script: |
          ./gradlew clean
          ./gradlew bundleRelease -Pandroid.injected.signing.store.file=keystore.jks \
                                  -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
                                  -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
                                  -Pandroid.injected.signing.key.password=$KEY_PASSWORD
    artifacts:
      - build/**/outputs/**/*.aab
