workflows:
  build-aab:
    name: Build AAB for Play Store
    max_build_duration: 30
    environment:
      groups:
        - github-secrets
      vars:
        JAVA_VERSION: 17

    scripts:
      - name: Make Gradle executable
        script: chmod +x gradlew

      - name: Auto-increment versionCode
        script: |
          echo "🔢 Auto-incrementing versionCode in build.gradle"
          FILE="app/build.gradle"
          VERSION_LINE=$(grep versionCode $FILE)
          VERSION_CODE=$(echo $VERSION_LINE | grep -o '[0-9]\+')
          NEW_VERSION_CODE=$((VERSION_CODE + 1))
          sed -i.bak "s/versionCode $VERSION_CODE/versionCode $NEW_VERSION_CODE/" $FILE
          echo "Updated versionCode to $NEW_VERSION_CODE"

      - name: Build AAB
        script: |
          ./gradlew clean
          ./gradlew bundleRelease

      - name: Commit updated build.gradle if changed
        script: |
          git config user.name "codemagic-bot"
          git config user.email "bot@codemagic.io"
          git remote set-url origin https://$GITHUB_TOKEN@github.com/mitbapl/SOAAnalyzerFinal.git

          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add app/build.gradle
            git commit -m "🤖 Auto-incremented versionCode to $NEW_VERSION_CODE"
            git push origin HEAD
          fi

    artifacts:
      - app/build/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - mitba.prashant@gmail.com
