workflows:
  build-aab:
    name: Build AAB with auto-increment versionCode
    max_build_duration: 30
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Make Gradle executable
        script: chmod +x gradlew

      - name: Auto-increment versionCode
        script: |
          FILE=app/build.gradle
          CODE=$(grep versionCode $FILE | head -1 | awk '{print $2}')
          NEWCODE=$((CODE + 1))
          echo "Current versionCode: $CODE"
          echo "Incrementing to: $NEWCODE"
          sed -i.bak "s/versionCode $CODE/versionCode $NEWCODE/" $FILE
          rm "$FILE.bak"

      - name: Commit updated build.gradle if changed
        script: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config user.name "codemagic-bot"
            git config user.email "bot@codemagic.io"
            git add app/build.gradle
            git commit -m "Auto-incremented versionCode to $NEWCODE"
            git push origin HEAD
          fi

      - name: Build AAB
        script: |
          ./gradlew clean
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/bundle/release/*.aab
