workflows:
  android-app:
    name: Unsigned AAB Build
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.example.soa"
    scripts:
      - name: Build Unsigned AAB with CLI Gradle
        script: |
          # ensure Android SDK is in PATH
          export ANDROID_HOME="$HOME/Android/Sdk"
          export PATH="$ANDROID_HOME/platform-tools:$PATH"
          
          # Use the system Gradle instead of wrapper
          gradle clean
          gradle bundleRelease
    artifacts:
      - app/build/outputs/bundle/**/*.aab
