workflows:
  build-apk:
    name: Build APK Directly (Release)
    max_build_duration: 30
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Make Gradle executable
        script: chmod +x gradlew
      - name: Build APK
        script: |
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - mitba.prashant@gmail.com
